name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest

    outputs:
      next-version: ${{ steps.increment-version.outputs.next-version }}
    
    steps:
      - name: Increment version
        id: increment-version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          CURRENT=$(gh release view --repo ${{ github.repository }} --json tagName --jq .tagName 2>/dev/null || true)
          echo "Current version: $CURRENT"

          if [ -z "$CURRENT" ]; then
            CURRENT="v0"
          fi

          NEXT_VERSION="v$(( ${CURRENT:1} + 1 ))"
          echo "Next version: $NEXT_VERSION"
          echo "next-version=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "$NEXT_VERSION" > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v6
        with:
          name: version
          path: version.txt

  build:
    runs-on: ubuntu-latest
    needs: get-version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Run make
      run: make

    - name: Rename artifact
      run: mv bin/shell bin/shell_${{ needs.get-version.outputs.next-version }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: shell_${{ needs.get-version.outputs.next-version }}
        path: bin/shell_${{ needs.get-version.outputs.next-version }}

  build-release:
    runs-on: ubuntu-latest
    needs: get-version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Run make release=1
      run: make release=1
    
    - name: Rename artifact
      run: mv bin/shell bin/shell_${{ needs.get-version.outputs.next-version }}-release

    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: shell_${{ needs.get-version.outputs.next-version }}-release
        path: bin/shell_${{ needs.get-version.outputs.next-version }}-release